openapi: 3.0.0
info:
  title: Qurio&Ans API
  description: Qurio&Ans app API documentation
  version: 1.0.0
  contact:
    name: Keena
    email: tolanijimoh1@gmail.com

servers:
  - url: https://qurioans.onrender.com
    description: Production server

paths:
  /qurioans/signup:
    post:
      summary: User Signup
      description: Register a new user account by providing userName, email and password.
      tags:
        - User - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserSignupRequest"
      responses:
        "201":
          description: User signed up successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User signed up successfully
                  status:
                    type: boolean
                    example: true
        "400":
          description: Invalid input or missing fields
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Input fields cannot be empty or invalid
                  status:
                    type: boolean
                    example: false
        "409":
          description: Username or email already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Username already exists, kindly pick another one
                  status:
                    type: boolean
                    example: false
        "500":
          description: Internal server error

  /qurioans/signin:
    post:
      summary: Login user
      description: Authenticates a user by validating email and password.

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: userPassword123
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User logged in successfully
                  status:
                    type: boolean
                    example: true
                  email:
                    type: string
                    example: user@example.com
                  role:
                    type: string
                    example: user
                  id:
                    type: string
                    example: 64fe81a9b9c41e001eaa1234
        "401":
          description: Invalid password
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid password
                  status:
                    type: boolean
                    example: false
        "403":
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User not found
                  status:
                    type: boolean
                    example: false
        "405":
          description: Empty input fields
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Input fields cannot be empty
                  status:
                    type: boolean
                    example: false
        "408":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error
