openapi: 3.0.0
info:
  title: Qurio&Ans API
  description: Qurio&Ans app API documentation
  version: 1.0.0
  contact:
    name: Keena
    email: tolanijimoh1@gmail.com

servers:
  - url: http://localhost:5003/
    description: Local development server
  - url: https://qurioans.onrender.com
    description: Production server

paths:
  /qurioans/signup:
    post:
      summary: User Signup
      description: Register a new user account by providing userName, email and password.
      tags:
        - User - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserSignupRequest"
      responses:
        "201":
          description: User signed up successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User signed up successfully
                  status:
                    type: boolean
                    example: true
        "400":
          description: Invalid input or missing fields
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Input fields cannot be empty or invalid
                  status:
                    type: boolean
                    example: false
        "409":
          description: Username or email already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Username already exists, kindly pick another one
                  status:
                    type: boolean
                    example: false
        "500":
          description: Internal server error

components:
  schemas:
    UserSignupRequest:
      type: object
      required:
        - userName
        - email
        - password

      properties:
        userName:
          type: string
          description: Unique username, at least 8 characters.
          minLength: 8
          example: johndoe123
        email:
          type: string
          format: email
          description: User email address.
          example: johndoe@example.com
        password:
          type: string
          format: password
          description: Password with at least 8 characters.
          minLength: 8
          example: StrongPass123!
